Inventory/Controllers/ComputerController.cs
using Inventory.Domain.ViewModels.Computers;
using Inventory.Service.Implementations;
using Inventory.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Controllers
{
    public class ComputerController : Controller
    {
        private readonly IComputerService _computerService;
        private readonly IQrCodeService _qrCodeService;

        public ComputerController(IComputerService computerService, IQrCodeService qrCodeService) =>
            (_computerService, _qrCodeService) = (computerService, qrCodeService);

        [Route("Computer/Index/{id}")]
        public IActionResult Index(int id)
        {
            var computer = _computerService.GetOneComputer(id);

            _qrCodeService.QrCodeGenerator($"https://localhost:44380/Computer/Index/{id}");

            return View(computer);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateComputer(UpdateComputerViewModel model)
        {
            var response = await _computerService.Update(model);

            if (response.StatusCode == Domain.Enum.StatusCode.Ok)
            {
                return Ok(new { description = response.Description });
            }

            return BadRequest(new { description = response.Description });
        }
    }
}

Inventory/Controllers/HomeController.cs
using Azure;
using Inventory.Domain.Filters;
using Inventory.Domain.ViewModels.Computers;
using Inventory.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Controllers
{
    public class HomeController : Controller
    {
        private readonly IComputerService _computerService;

        public HomeController(IComputerService computerService) =>
            _computerService = computerService;

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateComputerViewModel model)
        {
            var response = await _computerService.Create(model);

            if (response.StatusCode == Domain.Enum.StatusCode.Ok)
            {
                return Ok(new { description = response.Description });
            }

            return BadRequest(new { description = response.Description });
        }

        [HttpGet]
        public async Task<IActionResult> ComputerHandler(DeviceFilter filter)
        {
            var response = await _computerService.GetComputers(filter);

            return Json(new { data = response.Data });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _computerService.Delete(id);

            if (response.StatusCode == Domain.Enum.StatusCode.Ok)
            {
                return Ok(new { description = response.Description });
            }

            return BadRequest(new { description = response.Description });
        }
    }
}

Inventory/Views/Computer/Index.cshtml
@model ComputerViewModel

<div class="row">
    <form id="computerForm" class="col-md-6">
        <div>
            <input name="id" hidden value=@Model.Id />
            <input disabled name="inventoryNumber" id="inventoryNumber" class="form-group col-md-8 mb-3" value=@Model.InventoryNumber type="text" />
            <input disabled name="description" id="description" class="form-group col-md-8 mb-3" value=@Model.Description type="text" />
            <input disabled name="owner" id="owner" class="form-group col-md-8 mb-3" value=@Model.Owner type="text" />
            <input disabled name="location" id="location" class="form-group col-md-8 mb-3" value=@Model.Location type="text" />
            <input disabled name="additionDate" id="additionDate" class="form-group col-md-8 mb-3" value=@Model.AdditionDate type="datetime" />
        </div>
        <button disabled id="saveChanges" class="btn btn-primary col-md-3 mb-4">Сохранить</button>
        <button id="edit" class="btn btn-primary col-md-3 mb-4">Изменить</button>
    </form>
    <div class="row">
        <img src="~/QrCode/MyQR.png" class="col-md-2">
        <a href="~/QrCode/MyQR.png" download="MyQR.png">Скачать</a>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <script>

        $('#edit').on('click', function (event) {
            event.preventDefault();
            $('#inventoryNumber').prop("disabled", false);
            $('#description').prop("disabled", false);
            $('#owner').prop("disabled", false);
            $('#location').prop("disabled", false);
            $('#saveChanges').prop("disabled", false);
        });

        $('#saveChanges').on('click', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("UpdateComputer", "Computer")',
                data: $('#computerForm').serialize(),
                success: function (response) {
                    Swal.fire({
                        title: 'Информация',
                        text: response.description,
                        icon: 'success',
                        confimButtonText: 'Ok'
                    })
                },
                error: function (response) {
                    Swal.fire({
                        title: 'Информация',
                        text: response.responseJSON.description,
                        icon: 'error',
                        confimButtonText: 'Ok'
                    })
                }
            })
            $('#inventoryNumber').prop("disabled", true);
            $('#description').prop("disabled", true);
            $('#owner').prop("disabled", true);
            $('#location').prop("disabled", true);
            $('#saveChanges').prop("disabled", true);
        })

    </script>
}

Inventory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form id="createForm">
    <div>
        <input name="inventoryNumber" class="form-group col-md-8 mb-3" placeholder="Инв. номер" type="text" />
        <input name="description" class="form-group col-md-8 mb-3" placeholder="Описание" type="text" />
        <input name="owner" class="form-group col-md-8 mb-3" placeholder="Владелец" type="text" />
        <input name="location" class="form-group col-md-8 mb-3" placeholder="Локация" type="text" />
    </div>
    <button id="createTask" class="btn btn-primary col-md-3 mb-2">Создать</button>
</form>

<div class="row">
    <div class="form-group col-md-2">
        <label class="col-form-label">Инв. номер</label>
        <input name="inventoryFilter" type="text" class="form-control" />
    </div>
    <div class="form-group col-md-2">
        <label class="col-form-label">Описание</label>
        <input name="descriptionFilter" type="text" class="form-control" />
    </div>
    <div class="form-group col-md-2">
        <label class="col-form-label">Владелец</label>
        <input name="ownerFilter" type="text" class="form-control" />
    </div>
    <div class="form-group col-md-2 mb-3">
        <label class="col-form-label">Локация</label>
        <input name="locationFilter" type="text" class="form-control" />
    </div>
</div>

<div class="table-wrapper-scroll-y my-custom-scrollbar">
    <table class="table table-bordered table-dark table-hover table-striped mb-0" id="tableId">
        <thead>
            <tr>
                <th>Инв. номер</th>
                <th>Описание</th>
                <th>Владелец</th>
                <th>Локация</th>
                <th>Дата добавления</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>


@section Scripts
{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <script>
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
            },
            buttonsStyling: false
        })

        let dataTable = $('#tableId').DataTable({
            info: true,
            serverSide: true,
            searching: false,
            paging: false,
            sorting: false,
            ajax: {
                url: '@Url.Action("ComputerHandler")',
                method: 'GET',
                data: model
            },
            columns: [
                { data: 'inventoryNumber' },
                { data: 'description' },
                { data: 'owner' },
                { data: 'location' },
                { data: 'additionDate' },
                {
                    data: null,
                    sortable: false,
                    render: function (data, type) {
                        return '<button id="info" class="btn btn-success btn-sm center-block">Подробнее</button>'
                    }
                },
                {
                    data: null,
                    sortable: false,
                    render: function (data, type) {
                        return '<button id="delete" class="btn btn-danger btn-sm center-block">Удалить</button>'
                    }
                },
            ],
            createdRow: function(nRow, data) {
                var handlerDelete = function () {
                    console.log(data.id);
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete")',
                        data: { id: data.id },
                    })
                }

                var handlerInfo = function () {
                    console.log(data.id);
                    toComputer(data.id);
                }

                for (var i = 0; i < dataTable.columns().header().length - 1; i++) {
                    $('td', nRow).eq(i).css('cursor', 'pointer');

                    $('td', nRow).eq(i).on('click', null);
                }
                $('#info', nRow).on('click', handlerInfo);
                $('#delete', nRow).on('click', handlerDelete);
            }
        })

        function model() {
            return {
                InventoryNumber: $('input[name="inventoryFilter"]').val(),
                Description: $('input[name="descriptionFilter"]').val(),
                Owner: $('input[name="ownerFilter"]').val(),
                Location: $('input[name="locationFilter"]').val(),
            }
        }

        $('input[name="inventoryFilter"]').on('change', function () {
            dataTable.draw();
        })

        $('input[name="descriptionFilter"]').on('change', function () {
            dataTable.draw();
        })

        $('input[name="ownerFilter"]').on('change', function () {
            dataTable.draw();
        })

        $('input[name="locationFilter"]').on('change', function () {
            dataTable.draw();
        })

        function toComputer(id) {
            var url = '@Url.Action("Index", "Computer", new { id = "__id__" })';
            window.location.href = url.replace('__id__', id);
        }

        $('#createTask').on('click', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Home")',
                data: $('#createForm').serialize(),
                success: function (response) {
                    Swal.fire({
                        title: 'Информация',
                        text: response.description,
                        icon: 'success',
                        confimButtonText: 'Ok'
                    })
                },
                error: function (response) {
                    Swal.fire({
                        title: 'Информация',
                        text: response.responseJSON.description,
                        icon: 'error',
                        confimButtonText: 'Ok'
                    })
                }
            })
        })

    </script>
}

Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inventory.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">АГТУ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Inventory - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>